version: '2'
services:
  # Define a Telegraf service
  telegraf:
    image: telegraf
    container_name: telegraf
    volumes:
      - ./etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    links:
      - influxdb
    ports:
      - "8092:8092/udp"
      - "8094:8094"
      - "8125:8125/udp"
  # Define an InfluxDB service
  influxdb:
    image: influxdb
    container_name: influxdb
    volumes:
      - ./data/influxdb:/var/lib/influxdb
    ports:
      - "8086:8086"
  # Define a Grafana service
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    links:
      - influxdb
  # Define a NGINX service
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./etc/nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt/live/iod.proserve.nl/fullchain.pem:/etc/letsencrypt/live/iod.proserve.nl/fullchain.pem
      - /etc/letsencrypt/live/iod.proserve.nl/privkey.pem:/etc/letsencrypt/live/iod.proserve.nl/privkey.pem
    ports:         
      - "80:80"
      - "443:443"
    links:
      - grafana
