version: '2'
services:
  # Define a Telegraf service
  telegraf:
    image: telegraf:1.4.0
    volumes:
      - ./etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    links:
      - influxdb
    ports:
      - "8092:8092/udp"
      - "8094:8094"
      - "8125:8125/udp"
  # Define an InfluxDB service
  influxdb:
    image: influxdb:1.3.5
    volumes:
      - ./data/influxdb:/var/lib/influxdb
    ports:
      - "8086:8086"
