version: '2'
services:
  # Define a Telegraf service
  telegraf:
    image: telegraf
    container_name: telegraf
    volumes:
      - ./etc/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    links:
      - influxdb
    ports:
      - "8092:8092/udp"
      - "8094:8094"
      - "8125:8125/udp"
  # Define an InfluxDB service
  influxdb:
    image: influxdb
    container_name: influxdb
    volumes:
      - ./data/influxdb:/var/lib/influxdb
    ports:
      - "8086:8086"
  # Define a Grafana service
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "80:3000"
    #env_file:
    #  - 'env.grafana'
    links:
      - influxdb
